<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chainer</RootNamespace>
        <PackageId>Chainer</PackageId>

        <Authors>Nathan Pepin</Authors>
        <Title>Chainer - Chain of responsibility simplified</Title>
        <Company>Nathan pepin</Company>
        <PackageVersion>1.0.0</PackageVersion>
        <Product>Nathan Pepin</Product>
        <Description>Create chains of actions over a shared context. Create dymanically, or use via dependency injection.</Description>
        <PackageProjectUrl>https://github.com/nathanpepin/Chainer</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>chain of responsibility,pipeline</PackageTags>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Copyright>Nathan Pepin</Copyright>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Utilities\"/>
    </ItemGroup>

</Project>
